#!/bin/sh
#ch mode this file using the following command 
#chmod +x post_ubuntu_install
#then use the below command to run this script in batch 
#./post_ubuntu_install

# update & basics
sudo apt-get update
sudo apt install python3-pip -y
sudo apt-get install build-essential libgmp3-dev python3-dev -y
sudo apt-get install unrar
sudo apt-get install curl -y
sudo apt-get install ant  -y
sudo apt-get install git -y
sudo apt-get install wget -y
sudo apt-get install aptitude -y
sudo aptitude install unzip -y
sudo apt-get install synaptic -y



# install chrome 
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable




sudo apt-get update
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

#java  
java -version
sudo apt-get install openjdk-7-jdk
sudo apt-get install openjdk-8-jdk

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer


#sudo update-alternatives --config java
# set JAVA_HOME
sudo gedit /etc/environment

# add the below line at the end of file 
# JAVA_HOME="/usr/lib/jvm/java-8-oracle"
# JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"  # for ubnutu 16.04
# save and close
# source /etc/environment
echo $JAVA_HOME

# A nice tool to manage ppa
sudo add-apt-repository ppa:webupd8team/y-ppa-manager
sudo apt-get update
sudo apt-get install y-ppa-manager
sudo y-ppa-manager


# Node npm
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get update
sudo apt-get install -y nodejs
sudo apt-get install -y npm



# some node packages 
sudo npm install gulp -g
sudo npm install bower -g



# remmina remote desktop 
sudo apt-get remove remmina
sudo apt-get remove --auto-remove remmina
sudo apt-get purge remmina
sudo apt-get purge --auto-remove remmina
#add
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard



# Atom
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom


# postgres 9.6

deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt-get install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get upgrade
#sudo apt-get install postgresql-10 pgadmin4 
#sudo apt-get install postgresql-9.6 pgadmin4 
# postgis installtion ...
# sudo apt-get install postgresql-9.6-postgis-2.3



# tomcat8
sudo apt-get update
sudo apt-get install tomcat8
sudo apt-get install tomcat8-docs tomcat8-admin tomcat8-examples

# tomcat8 username password set 
sudo gedit /etc/tomcat8/tomcat-users.xml

<role rolename="manager-gui"/>
<role rolename="admin-gui"/>
<user username="tomcat8" password="tomcat8" roles="manager-gui,admin-gui"/>

sudo gedit /etc/default/tomcat8
#   JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Xmx512m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC"

sudo service tomcat8 restart

# Android set the path in file called .bashrc in the home folder 

#export ANDROID_HOME=$HOME/Android/sdk
#export PATH=$PATH:$ANDROID_HOME/tools
#export PATH=$PATH:$ANDROID_HOME/platform-tools



# QGIS 3.0.2
sudo add-apt-repository "deb     https://qgis.org/debian bionic main"
sudo add-apt-repository "deb-src https://qgis.org/debian bionic main"
wget -O - https://qgis.org/downloads/qgis-2017.gpg.key | gpg --import
gpg --fingerprint CAEB3DC3BDF7FB45
gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -
sudo apt-get update && sudo apt-get install qgis python-qgis qgis-plugin-grass






